<?php

/**
 * @file
 * Contains cwd_events_localist_pull.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;
use \Drupal\node\Entity\Node;
use Drupal\file\Entity\File;
use Drupal\cwd_events_localist_pull\LocalistProcessor;

/**
 * Implements hook_help().
 */
function cwd_events_localist_pull_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cwd_events_localist_pull module.
    case 'help.page.cwd_events_localist_pull':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to import events from localist (CU Calendar, Weill Calendar, etc.) into nodes of a specified content type.') . '</p>';
      return $output;

    default:
  }
}

function cwd_events_localist_pull_cron() {
    // updating deprecated code
    // $query = \Drupal::service('entity.query')->get('localist_pull');
    $query = \Drupal::entityQuery('localist_pull');
    $entity_ids = $query->execute();
    $config_storage = \Drupal::entityTypeManager()->getStorage('localist_pull');
    $configs = $config_storage->loadMultiple($entity_ids);
    $file_system = \Drupal::service('file_system');
    foreach ($configs as $config) {
      $processor = new LocalistProcessor($config, $file_system);
      $url = $processor->create_localist_url();
      $processor->process_url_pull($config->get('localist_id_field_name'),$url);
    }

}
