localist_pull.localist_pull.*:
  type: config_entity
  label: 'localist_pull entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: string
      label: 'URL'
    localist_departments:
      type: string
      label: 'URL'
    localist_keywords:
      type: string
      label: 'URL'
    localist_count:
      type: string
      label: 'URL'
    localist_date:
      type: string
      label: 'URL'
    event_machine_name:
      type: string
      label: 'URL'
    localist_id_field_name:
      type: string
      label: 'URL'
    localist_url_field_name:
      type: string
      label: 'URL'
    localist_location_field_name:
      type: string
      label: 'URL'
    localist_date_field_name:
      type: string
      label: 'URL'
    localist_end_date_field_name:
      type: string
      label: 'URL'
    localist_description_field_name:
      type: string
      label: 'URL'
    localist_image_field_name:
      type: string
      label: 'URL'
    update_events_bool:
      type: boolean
      label: 'Should we update existing events'
    publish_events_bool:
      type: boolean
      label: 'Should we update publish all fed in events'
