cwd_events_localist_pull.localist_pull.*:
  type: config_entity
  label: 'localist_pull entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: string
      label: 'URL'
    localist_departments:
      type: string
      label: 'Departments'
    localist_keywords:
      type: string
      label: 'Keywords'
    localist_count:
      type: string
      label: 'Event Count'
    localist_date:
      type: string
      label: 'Date'
    event_machine_name:
      type: string
      label: 'Event Machine Name'
    localist_id_field_name:
      type: string
      label: 'Localist event ID'
    localist_url_field_name:
      type: string
      label: 'Localist event URL'
    localist_location_field_name:
      type: string
      label: 'Localist event location'
    localist_date_field_name:
      type: string
      label: 'Localist event date'
    localist_end_date_field_name:
      type: string
      label: 'Localist event end date'
    localist_description_field_name:
      type: string
      label: 'Localist event description'
    localist_image_field_name:
      type: string
      label: 'Localist event image'
    localist_tag_field_name:
      type: string
      label: 'Localist event department tags'
    localist_department_taxonomy:
      type: string
      label: 'Department Taxonomy'
    update_events_bool:
      type: boolean
      label: 'Should we update existing events'
    publish_events_bool:
      type: boolean
      label: 'Should we update publish all imported events'
    pull_specified_departments:
      type: boolean
      label: 'Should we pull only the specified departments as tags'
